#!/usr/bin/env perl
use strict; use warnings; use v5.30;
use FindBin;

#Global variables that you probably don't want to change. They are here to prevent hardcoding
my $name = "CIBU";
my $tmpmountpointprefix = "/tmp/$name-mnt-";


#Prints an error message passed as an argument and exit with code 1
sub myerror {
  say "ERROR: @_";
  say "Depending on where in the script this error happened, you might want to umount newly created partitions and remove their mountpoints. (Their paths are '${tmpmountpointprefix}*')";
  exit(1);
}

#Runs a system command passed as an argument, and print it before running it. If the command fails (exit code != 0), mentions it in an error message and exits with code 1.
sub mysystem {
  say "### Running: '@_'";
  system(@_) == 0 or myerror "Command '@_' failed with exit code $?";
}

#Checks if the programs passed as arguments are available in the system's $PATH. If a program is not found, prints an error message and exit with code 1.
sub check_available_programs {
  say "Checking for required programs...";
  foreach(@_) {
    my $path = `which $_ 2>/dev/null`;
    if($? == 0 && $path =~ /^\/.*$_$/) {
      print "Found required program '$_' at path: $path";
    } else {
      myerror "Required program '$_' not found in your \$PATH. Please install it and make sure it's available in your \$PATH before running this script.";
    }
  }
  say "All required programs are available.";
}

sub showdisclaimer {
    print << "END";

This script will format a chosen block device (USB-stick, disk, ...) or disk image file with ${name}'s recommended set-up.
Although I've tried to be careful, a bug could potentially wipe your whole computer !  So make sure you have a recent backup before executing this script !
Read the documentation in 'README.md' and the license in 'LICENSE' before running this script.

END
}

#Asks the user for confirmation to continue. Exits the script with return code 1 if the user doesn't enter 'y' or 'yes'. If an argument is passed then this will be the question instead of the default one.
sub ask_for_confirmation {
    my $defaultmessage = "Enter 'yes' to confirm or 'no' to cancel: ";
    my $message = $defaultmessage;
    $message = shift if @_;
    print $message;
    if(<STDIN> !~ /^\s*y(es)?\s*$/i) {
      say "Script cancelled by user.";
      exit(1);
    }
}

#Returns a hash with the uid and gid of the user starting the script. If the original user is root quit with return code 1
#If the user is not root at this point in time restart this script but run it with sudo to give it all necessary permissions
sub run_as_root {
    my $user = {};
    if($> == 0 and not exists $ENV{SUDO_USER}) {
        myerror "This script should not be run as root. Run it as a normal user. It will use sudo to become root."
    }
    if(exists $ENV{SUDO_USER} && exists $ENV{SUDO_UID} && exists $ENV{SUDO_GID}) {
        $user->{uid} = $ENV{SUDO_UID};  #SUDO_UID is the UID of the user who invoked sudo
        $user->{gid} = $ENV{SUDO_GID};  #SUDO_GID is the GID of the user who invoked sudo
    } else {
        exec('sudo', '-E', $0, @ARGV) or myerror "Failed to re-run the script with sudo. Please run the script as a normal user and make sure you have sudo installed and configured correctly.";
    }
    return $user;
}

#Checks if the given device is a CIBU device by using lsblk to check if the first partition has the label that the first partition of CIBU-device should have (according to $wantedpartitions).
#Accepts the $wantedpartitions settings as argument to check whether the device is a CIBU-device. Returns 1 if the device is a CIBU-device, otherwise returns undef
sub is_cibu_device {
  my ($device, $wanted_partitions) = @_;
  my @labels = split("\n", `lsblk -o label -pn $device`);
  if(exists $labels[1] && $labels[1] eq $wanted_partitions->[0]->{label}) { return 1; } else { return undef; } #$label[1] because $labels[0] is $device itself
}


#Creates a description key for a hash as described in show_info_about_device and returns the description
sub create_device_description {
    my $deviceinfo = shift;
    my $description = $deviceinfo->{removable} ? "Removable " : "Non-removable ";
    $description .= $deviceinfo->{size} . " ";
    if($deviceinfo->{cibu}) {
      $description .= "device with a $name installation (that I can reinstall/update) ";
    } else {
      $description .= "device without $name ";
    }
    if($deviceinfo->{model} ne "") {
      $description .= "($deviceinfo->{model})";
    }
    return $description;
}

#Returns a hash with as keys the available block devices and as values hashes as described in show_info_about_device
#Accepts the $wantedpartitions settings as argument to check whether the device is a CIBU-device
sub find_available_block_devices {
    my $wantedpartitions = shift;
    my @blockdevices = split("\n", `lsblk -pndo NAME,RM,SIZE,MODEL`);
    my $devicetypes = {};
    foreach(@blockdevices) {
      if(/^(\S+)\s+(\d)\s+(\S+)\s+(.*)\s*$/) {
        my $path = $1; my $removable = $2; my $size = $3; my $model = $4;
        next if($path =~ /^\/dev\/sr\d+$/);
        $devicetypes->{$path} = { path => $path, removable => $removable, size => $size, model => $model, cibu => is_cibu_device($path, $wantedpartitions) };
        $devicetypes->{$path}->{description} = create_device_description($devicetypes->{$path});
      }
    }
    return $devicetypes;
}

#Accepts a hash with info about the device and prints the description and the output of 'fdisk -l' for the device.
#The hash has the following keys: 'path', 'removable' (1 if it is), 'size' (human readable), 'model', 'cibu' (1 if it is a CIBU-device) and 'description'
sub show_info_about_device {
    my $device = shift;
    say "";
    say "Device '$device->{path}' is a $device->{description}.";
    say "The partition layout according to fdisk is :";
    mysystem("fdisk -l $device->{path}");
}

#Asks the user to choose a block device from a list of available block devices or to enter a path to a block device. Returns the chosen block device.
#If the user enters 0 or a path that is not a block device the script will be cancelled with an error message.
#The last number will be used to show detailed info of all block devices and afterwards this function will be called again.
#When we implement the option to create a disk image file in the future, the check for a block device will be removed
#Receives the $wantedpartitions setting because it will be used to check whether a device is a CIBU-device
sub choose_device {
    my $wantedpartitions = shift;
    my $blockdevices = find_available_block_devices($wantedpartitions);
    my @sorteddevices = sort keys %$blockdevices;
    my @options = ("Cancel");
    foreach(@sorteddevices) {
      push @options, "$_ -> $blockdevices->{$_}->{description}";
    }
    print << 'END';
Choose the number of a blockdevice to overwrite. Choose option 0 to cancel.
You can also enter the full path. This will be useful IN THE FUTURE if you want to create a disk image file instead of a physical block device.
(Disk images is a feature that is not yet implemented)
END
    my $i;
    for($i=0; $i<@options; $i++) {
      say "[$i] $options[$i]";
    }
    say "[$i] Show detailed info of all block devices above first";
    print "Choose a optionnumber or enter a path: "; my $answer = <STDIN>; chomp $answer;
    if($answer =~ /^\s*0\s*$/) {  #The first option is not part of @devices
        say "Script cancelled by user."; exit(1);
    } elsif($answer =~ /^\s*$i\s*$/) {  #Neither is the last
        show_info_about_device($blockdevices->{$_}) foreach(@sorteddevices);
        return choose_device($wantedpartitions);
    } elsif($answer =~ /^\s*(\d+)\s*$/ && exists $options[$1]) {
        deviceinfo_and_confirmation($blockdevices->{$sorteddevices[$1-1]}); # -1 because the devices start counting at 1 in the options
        return $sorteddevices[$1-1];
    } elsif($answer =~ /^\s*(\S.*?)\s*$/ && -b $1) {
        return $1;
    } else {
        myerror "Invalid input. Please enter a valid number or path to a (existing) file or block device.";
    }
}

#Checks if any of the partitions on the given device are mounted. If a mounted partition is found, prints an error message and exits with code 1.
sub check_if_mounted {
    my $device = shift;
    say "Checking if any partitions on '$device' are mounted...";
    my @partitions = `lsblk -o mountpoint -n $device`;
    foreach(@partitions) {
        chomp;
        unless(/^\s*$/) {
            print <<END;    #We don't use myerror because no warning about mountpoints is needed.

Sorry, quiting... $device has one or more partitions that are still mounted. (I already found a partition mounted at '$_').
Please unmount all partitions on the device before running this script.
(At this point in the script I don't umount things myself for safety reasons.
When the device get's new partitions later, I will do mounting and umounting myself)
END
            exit(1);
        }
    }
    say "No partitions on '$device' are mounted.";
}

#Prints some information about the given device (as hash as described in show_info_about_device) and asks the user to confirm
sub deviceinfo_and_confirmation {
    my $device = shift;
    say "You have chosen to overwrite '$device->{path}', here is some information about it:";
    show_info_about_device($device);
    ask_for_confirmation("\nIf you are sure you have chosen the correct device, then please enter 'yes' to confirm and continue, otherwise enter 'no' to cancel: ");
}

#Finds the partitions on the given device and returns them as a list.
sub find_partitions_on_device {
    my $device = shift;
    my $fdisk_output = `fdisk -l $device`;
    my @partitions;
    foreach(split("\n", $fdisk_output)) {
        if(/^\s*($device\d+)\s+/) {
            push @partitions, $1;
        }
    }
    return \@partitions;
}

#Wipes the filesystem signatures of the partitions on the given devices, wipes the partition table and creates a new GPT partition table
sub wipe_and_create_table {
    my ($device, $ddlength) = @_;
    my $partitions = find_partitions_on_device($device);
    say "Wiping '$device' and creating a new GPT partition table on it...";
    foreach(@$partitions) {
        mysystem("dd if=/dev/zero of=$_ $ddlength conv=fsync"); #Wipe the beginning of each partition, $ddlength is a combination of the bs and count options of dd
    }
    mysystem("sgdisk --zap-all $device"); #Wipe the partition table
    mysystem("sgdisk --mbrtogpt $device"); #Create a new GPT partition table
    mysystem("partprobe $device && sleep 3"); # Tell the OS about the new partition table
    say "$device has been wiped and a new GPT partition table has been created on it.";
}

#Creates 3 partitions on the device gives as 1st argument. The 2nd argument is the wanted partition layout (see the Settings-section).
#The 3rd partition will receive the special GUID and typecode needed for GRUB to use it as BIOS Boot partition
sub create_partitions {
    my ($device, $wantedpartitions) = @_;
    my $cibupartsize = $wantedpartitions->[0]->{size};
    my $biospartsize = $wantedpartitions->[2]->{size};
    say "Creating the 3 partitions on '$device' needed by $name.";
    say "The 1st partition will be used for $name and will have a size of $cibupartsize, the 2nd partition for the iso files and the 3rd partition will be used as the BIOS Boot partition by GRUB.";
    mysystem("sgdisk --new=1:0:+$cibupartsize $device"); # Create the first partition, starting at the beginning of the device, and using the specified size
    mysystem("sgdisk --new=3:-$biospartsize:0 --typecode=3:ef02 --partition-guid=3:21686148-6449-6E6F-744E-656564454649 $device"); # Create the third partition, starting at the end of the device, and using the specified size.
    #The 3rd partition will be used as the BIOS Boot partition by GRUB, so we have to make sure that it is 1MB, uses 21686148-6449-6E6F-744E-656564454649 as special GUID and typecode ef02 to indicate this
    mysystem("sgdisk --new=2:0:0 $device"); # Create the second partition, using the remaining space on the device
    mysystem("partprobe $device && sleep 3"); #Tell the OS about the new partitions
    say "The 3 partitions needed by $name have been created on '$device'.";
}

#Formats $device according to $wantpartentry (it's entry in $wantedpartitions)
sub mkfs {
  my ($device, $wantpartentry) = @_;
  say "Formatting $device as $wantpartentry->{label}";
  my $mkfscmd = $wantpartentry->{mkfs};
  $mkfscmd=~s/WANTEDLABEL/$wantpartentry->{label}/;
  $mkfscmd=~s/PARTPATH/$device/;
  mysystem("Partition $wantpartentry->{label} has been formatted");
}

#Labels and formats the partitions on the device given as 1st argument. The 2nd argument is the wanted partition layout (see the Settings-section).
#Returns a arrayref with the paths of the first and second partition
sub name_and_format_partitions {
    my ($device, $wantedpartitions) = @_;
    my $cibupartname = $wantedpartitions->[0]->{label};
    my $isopartname = $wantedpartitions->[1]->{label};
    my $biospartname = $wantedpartitions->[2]->{label};
    say "Naming and formatting the partitions on '$device'.";
    say "The first partition will be named '$cibupartname' and formatted as FAT32, the second partition will be named '$isopartname' and formatted as ext4, and the third partition will be named 'BIOS Boot' and left unformatted.";
    mysystem("sgdisk --change-name=1:'$cibupartname' $device");
    mysystem("sgdisk --change-name=2:'$isopartname' $device");
    mysystem("sgdisk --change-name=3:'$biospartname' $device");
    mysystem("partprobe $device && sleep 3"); #Tell the OS about the new partition names, before we format them
    say "Naming the partions on '$device' is done. Now formatting the partitions...";
    my ($cibupart, $isopart) = @{find_partitions_on_device($device)}[0,1];   #Partitions are not always just the device followed by a number
    mkfs($cibupart, $wantedpartitions->[0]);
    mkfs($isopart, $wantedpartitions->[1]);
    mysystem("partprobe $device && sleep 3"); #Tell the OS about the new partition changes
    say "The partitions on '$device' have been named and formatted.";
    return [$cibupart, $isopart];
}

#Checks if grub2-install or grub-install is available on the system, and returns a hash with a key 'installer' with this command as value.
#This hash also has a key 'configdir' that has the name of the grub config directory of the grub on your system as value (not the full path, only the ending which should be 'grub2' or 'grub').
#If neither grub2-install nor grub-install is found, prints an error message and exits with code 1.
sub grub_grub2_choice {
    say "Checking for grub or grub2";
    my $grubversion = {};
    my $path = `which grub2-install 2>/dev/null`;
    if($? == 0 && $path =~ /^\/.*grub2-install$/) {
      say "Found grub2-install";
      $grubversion->{installer} = 'grub2-install';
      $grubversion->{configdir} = 'grub2';
    } else {
        $path = `which grub-install 2>/dev/null`;
        if($? == 0 && $path =~ /^\/.*grub-install$/) {
          say "Found 'grub-install'";
          $grubversion->{installer} = 'grub-install';
          $grubversion->{configdir} = 'grub';
        } else {
          myerror "'grub2-install' or grub-install commands not found.";
        }
    }
    return $grubversion;
}

#Returns the absolute to the grub2 config directory which should be located in the same directory as this script. Prints an error message and exits with code 1 if the grub2 config directory or the grub.cfg file inside it is not found.
sub find_and_check_grub_dir {
    my $grubconfigdir = $FindBin::Bin . '/grub2';
    return $grubconfigdir if -d $grubconfigdir && -f "$grubconfigdir/grub.cfg";
    myerror "grub.cfg not found.";
}

#Unmounts the partitions passed as arguments if they are mounted. If a partition is not mounted, it will be skipped. If a partition is mounted multiple times, they will all be unmounted.
sub umount {
    my @partitions = @_;
    say "Checking if any of the following partitions are mounted and unmounting them if they are: @partitions";
    my $mountoutput = `mount`;
    if($? != 0) {
      myerror "Failed to get mount output.";
    }
    my $mounts = {};
    foreach(split("\n", $mountoutput)) {
      if(/^\s*(\S+)\s+on\s+(\S+)/) {
        if(exists $mounts->{$1}) {
          push @{$mounts->{$1}}, $2;
        } else {
          $mounts->{$1} = [$2];
        }
      }
    }
    foreach my $part (@partitions) {
      if(exists $mounts->{$part}) {
        foreach my $mnt (@{$mounts->{$part}}) {
          say "Unmounting $part from $mnt";
          mysystem("umount $mnt");
        }
      }
    }
    say "All specified partitions are now unmounted.";
}

#Mount the partition passed as an argument on a temporary directory and returns the absolute path of the mountpoint.
sub mount {
    my $partition = shift;
    say "Mounting $partition...";
    my $dir = `mktemp -d ${tmpmountpointprefix}XXXXXX`; chomp($dir);
    myerror "Failed to create temporary directory for mounting $partition." if($? != 0);
    mysystem("mount $partition $dir");
    say "$partition is now mounted on $dir.";
    return $dir;
}

#Checks if the grub on the system has support for BIOS and/or EFI boot mode by checking if the directories /usr/lib/grub/i386-pc and /usr/lib/grub/x86_64-efi exist.
#Returns a hash with keys 'BIOS' and 'EFI' with value 1 if support for that boot mode is found. If no support for either boot mode is found, prints an error message and exits with code 1.
sub check_bios_efi_support {
  my $support = {};
  $support->{BIOS} = 1 if( -d '/usr/lib/grub/i386-pc');
  $support->{EFI} = 1 if( -d '/usr/lib/grub/x86_64-efi');
  if(keys(%$support) == 0) {
    myerror "Neither support for BIOS or EFI was found in your grub";
  }
  if(exists $support->{BIOS}) {
    say "Grub BIOS support found.";
  } else {
    say "WARNING: no /usr/lib/grub/i386-pc dir. Skipping Grub BIOS support";
  }
  if(exists $support->{EFI}) {
    say "Grub EFI support found.";
  } else {
    say "WARNING: no /usr/lib/grub/x86_64-efi dir. Skipping Grub EFI support";
  }
  return $support;
}

#Installs GRUB on the given device and partition, for the boot modes supported by the grub on the system.
#1st argument is the grub installer command to use (grub-install or grub2-install),
#2nd argument is the hash with the supported boot modes returned by the check_bios_efi_support function
#3rd argument is the mountpoint of the first partition on which the boot files will be installed
#4th argument is the device on which to install grub
sub install_grub {
  my ($grubinstaller, $support, $part1mountpoint, $device) = @_;
  if(exists $support->{BIOS}) {
    say "Installing GRUB for BIOS boot mode...";
    mysystem("$grubinstaller --target=i386-pc --boot-directory '$part1mountpoint/boot' $device");
    say "GRUB installed for BIOS boot mode.";
  }
  if(exists $support->{EFI}) {
    say "Installing GRUB for EFI boot mode...";
    mysystem("$grubinstaller --target=x86_64-efi --removable --no-nvram --efi-directory '$part1mountpoint' --boot-directory '$part1mountpoint/boot' $device");
    say "GRUB installed for EFI boot mode.";
  }
}

#Copies the GRUB configuration files from the directory in the 1st argument to the directory in the 2nd argument. It is expected that:
# - The from-directory should be the absolute path of the grub2 config directory that is located in the same directory as this script
# - The to-directory is 'boot/grub' or 'boot/grub2' on the mounted first partition of the device, depending on the grub version found on the system. Also as absolute path.
sub copy_grub_config {
  my ($fromdir, $todir) = @_;
  say "Copying GRUB configuration to the device...";
  mysystem("rsync -rt --delete --exclude=i386-pc --exclude=x86_64-efi --exclude=fonts -- $fromdir/ $todir/");
  say "GRUB configuration copied.";
}

#Creates the directory layout for the ISO files. It is expected that:
# - The 1st argument is the partition that will be used for the ISO files. It is expected that this partition already has the correct label and (empty) filesystem.
# - The 2nd argument is the absolute path of the grub config directory on the first partition of the device. It is expected that CIBU is installed and that it's mounted
#   The distro config files in the grub2 config directory there should be named in the format 'inc-<distroname>.cfg'.
# - The 3rd argument is the name of the directory that will be created on the second partition to put the ISO files in.
# - The 4rd argument is a hash with the uid and gid of the user who invoked sudo
# The result will be a directory named $isosdir with for each <distroname> a subdir. And they will all get the UID and GID of the user who invoked sudo.
# Returns the mount point of the partition with the isos
sub create_isos_dirs {
  my ($isospart, $grubconfigdir, $isosdir, $user) = @_;
  say "Creating the directory layout for the partition for ISO files...";
  say ""; umount($isospart); #Just in case it's automounted
  my $isosmnt = mount($isospart);
  for my $distroconfig (glob("$grubconfigdir/*")) {
    $distroconfig =~ /^.*\/inc-(\S+)\.cfg$/ or next;
    mysystem("mkdir -p '$isosmnt/$isosdir/$1'");
  }
  mysystem("chown -R $user->{uid}:$user->{gid} '$isosmnt/$isosdir'");
  say "Directory layout for ISO files created. (A dir name '$isosdir' with subdirs for each distro where you can put the ISO files for that distro)";
  return $isosmnt;
}

#Create a new cibu device but don't install the cibu system on it yet.
#$wantedpartitions is the partition layout (see the Settings-section), $ddlength is the length (as dd options) that will be wiped with dd in the beginning of all old partitions
#Returns a arrayref with the path of the partition with the cibu system and the path of the partition for the ISO files.
sub create_new_device {
    my ($device, $wantedpartitions, $ddlength) = @_;
    say "Preparing a device for $name creation...";
    say ""; check_if_mounted($device);
    say ""; wipe_and_create_table($device, $ddlength);
    say ""; create_partitions($device, $wantedpartitions);
    say ""; my ($cibupart, $isopart) = @{name_and_format_partitions($device, $wantedpartitions)};
    say "Device '$device' is now ready for $name installation. The partition with the $name system is '$cibupart' and the partition for the ISO files is '$isopart'.";
    return [$cibupart, $isopart];
}

#Installs cibu on a device that already has the correct partition table.
#First argument is the device, 2nd argument the cibu partition
#It is expected that the cibu partition already has the correct label and (empty) filesystem. Returns a arrayref with the mountpoint of the cibu partition and the path of the config dir there
sub install_cibu {
    my ($device, $cibupart) = @_;
    say "Installing $name on the device...";
    say ""; my $grubversion = grub_grub2_choice();
    say ""; my $grubconfigdir = find_and_check_grub_dir();
    say ""; umount($cibupart); #Just in case it's automounted
    say ""; my $cibumnt = mount($cibupart);
    say ""; my $support = check_bios_efi_support();
    say ""; install_grub($grubversion->{installer}, $support, $cibumnt, $device);
    say ""; copy_grub_config($grubconfigdir, "$cibumnt/boot/$grubversion->{configdir}");
    return [$cibumnt, $grubconfigdir];
}

#If $device is not a $cibudevice, prepares it using create_new_device(). (see info there about the arguments)
#If it is, it just formats the CIBUSYS pratition unless it's asked for a full reinstall in which case it also calls create_new_device()
#In both case an arrayref with the paths of the partition of the cibusystem and that of the one with the iso files is returned
sub create_device_if_wanted {
  my ($device, $wantedpartitions, $ddlength) = @_;
  my $createdevice = 1;
  if(is_cibu_device($device, $wantedpartitions)) {
    say "The device you have chosen already has a $name installation on it. You can choose to wipe device completely or just do a reinstall/update";
    say "If you choose to skip wiping, your partition with the ISO files will be kept intact";
    print "Enter 'yes' to reinstall/update the $name system on the first partition so that you keep the partition with the ISO files intact: ";
    $createdevice = undef if(<STDIN> =~ /^\s*y(es)?\s*$/i);
  }
  if($createdevice) {
    say ""; return create_new_device($device, $wantedpartitions, $ddlength);
  }
  my [$cibupart, $isopart] = @{find_partitions_on_device($device)}[0,1];   #Partitions are not always just the device followed by a number
  #TODO the 3 lines are also done in name_and_format_partitions(), put them in a seperate function
  my $cibupartname = $wantedpartitions->[0]->{label};
  mysystem("mkfs.fat -I -F 32 -n $cibupartname $cibupart"); # Format the first partition as FAT32, and set its label
  mysystem("partprobe $device && sleep 3"); #Tell the OS about the new partition changes
  return [$cibupart, $isopart];
}

#Settings (Don't mess around with them, the variablenames might change in the future)
my $wantedpartitions = [
  { label => 'CIBUSYS', size => '100M', mkfs => 'mkfs.fat -I -F 32 -n WANTEDLABEL PARTPATH'},
  { label => 'ISOS', mkfs => 'mkfs.ext4 -F -L WANTEDLABEL PARTPATH'}, #size is undefined because we want to use the remaining space on the device for this partition
  { label => 'BIOS Boot', size => '1M'} ];    #mkfs is undefined because the grub installer will handle this
my $isosdir = 'isos';   #Don't change this because configfiles in the grub2 dir depend on this name
my $ddlength = 'bs=512 count=1024'; #The options given to dd to define the length that will be wiped in the beginning of the old partitions

#Preparation/checks
my $user = run_as_root();
showdisclaimer();
ask_for_confirmation("Have you read, understood & fully accepted the disclaimer and the rest of the text above ?\nPlease enter 'yes' to accept and continue, otherwise enter 'no' to cancel: ");
say ""; check_available_programs(qw(lsblk fdisk sgdisk partprobe mkfs.fat mkfs.ext4 mount mktemp rsync mount umount mkdir chown));
say ""; my $device = choose_device($wantedpartitions);
say ""; my ($cibupart, $isopart) = @{create_device_if_wanted($device, $wantedpartitions, $ddlength)};
say ""; my ($cibumnt, $grubconfigdir) = @{install_cibu($device, $cibupart)};
say ""; my $isosmnt = create_isos_dirs($isopart, $grubconfigdir, $isosdir, $user);
#Finishing up
say ""; umount($cibupart, $isopart);
say ""; mysystem("rm -rf '$cibumnt' '$isosmnt'"); #Remove the temporary mountpoints
say "All done ! You can now copy your ISO files to the '$isosdir' directory on the second partition of the device and boot from it to use $name. (The partition is '$isopart and has the label '$wantedpartitions->[1]->{label}')";
