#!/usr/bin/env perl
use strict; use warnings; use v5.30;
use File::Temp qw/tempdir/;
use Cwd qw/getcwd/;

#Global variables that you probably don't want to change. They are here to prevent hardcoding
my $tmpmountpointprefix = "/tmp/CIBU-mnt-";
#WANTEDLABEL and PARTPATH in the mkfs entries will be replaced by the actual label and partition path when the mkfs function is called
my $wantedpartitions = [
    { label => 'CIBUSYS', size => '100M', mkfs => 'mkfs.fat -I -F 32 -n WANTEDLABEL PARTPATH'},
    { label => 'ISOS', mkfs => 'mkfs.ext4 -F -L WANTEDLABEL PARTPATH'}, #size is undefined because we want to use the remaining space on the device for this partition
    { label => 'BIOS Boot', size => '1M'}
];    #mkfs is undefined because the grub installer will handle this
my $isosdir = 'isos';   #Don't change this because configfiles in the grub2 dir depend on this name
my $ddlength = 'bs=512 count=1024'; #The options given to dd to define the length that will be wiped in the beginning of the old partitions
my $settings; #Global variable to hold the settings read from the commandline options


#Prints an error message passed as an argument and exit with code 1
sub myerror {
    say "ERROR: @_";
    say "Depending on where in the script this error happened, you might want to umount newly created partitions and remove their mountpoints. (Their paths are '${tmpmountpointprefix}*')";
    exit(1);
}

#Prints a message passed as an argument unless the quiet option is set in the settings hash
sub mysay {
    say @_ unless $settings->{quiet};
}

#Runs a system command passed as an argument, and print it before running it. If the command fails (exit code != 0), mentions it in an error message and exits with code 1.
sub mysystem {
    mysay "### Running: '@_'";
    system(@_) == 0 or myerror "Command '@_' failed with exit code $?";
}

#Checks if the programs passed as arguments are available in the system's $PATH. If a program is not found, prints an error message and exit with code 1.
sub check_available_programs {
    mysay "Checking for required programs...";
    foreach(@_) {
        my $path = `which $_ 2>/dev/null`;
        if($? == 0 && $path =~ /^\/.*$_$/) {
            chomp $path;
            mysay "Found required program '$_' at path: $path";
        } else {
            myerror "Required program '$_' not found in your \$PATH. Please install it and make sure it's available in your \$PATH before running this script.";
        }
    }
    mysay "All required programs are available.";
}

sub showdisclaimer {
    mysay << "END";

This script will format a chosen block device (USB-stick, disk, ...) or disk image file with CIBU's recommended set-up.
Although I've tried to be careful, a bug could potentially wipe your whole computer !  So make sure you have a recent backup before executing this script !
Read the documentation in 'README.md' and the license in 'LICENSE' before running this script.

END
}

#Asks the user for confirmation to continue. Exits the script with return code 1 if the user doesn't enter 'y' or 'yes'. If an argument is passed then this will be the question instead of the default one.
sub ask_for_confirmation {
    my $defaultmessage = "Enter 'yes' to confirm or 'no' to cancel: ";
    my $message = $defaultmessage;
    $message = shift if @_;
    print $message;
    if($settings->{force}) {
        mysay "Force option is set, automatically confirming.";
        return;
    }
    if(<STDIN> !~ /^\s*y(es)?\s*$/i) {
        mysay "Script cancelled by user.";
        exit(1);
    }
}

#Returns a hash with the uid and gid of the user starting the script. If the original user is root quit with return code 1
#If the user is not root at this point in time restart this script but run it with sudo to give it all necessary permissions
sub run_as_root {
    my $user = {};
    if($> == 0 and not exists $ENV{SUDO_USER}) {
        myerror "This script should not be run as root. Run it as a normal user. It will use sudo to become root."
    }
    if(exists $ENV{SUDO_USER} && exists $ENV{SUDO_UID} && exists $ENV{SUDO_GID}) {
        $user->{uid} = $ENV{SUDO_UID};  #SUDO_UID is the UID of the user who invoked sudo
        $user->{gid} = $ENV{SUDO_GID};  #SUDO_GID is the GID of the user who invoked sudo
    } else {
        exec('sudo', '-E', $0, @ARGV) or myerror "Failed to re-run the script with sudo. Please run the script as a normal user and make sure you have sudo installed and configured correctly.";
    }
    return $user;
}

#Checks if the given device is a CIBU device by using lsblk to check if the first partition has the label that the first partition of CIBU-device should have (according to $wantedpartitions).
#Returns 1 if the device is a CIBU-device, otherwise returns undef
sub is_cibu_device {
    my ($devpath) = @_;
    my @labels = split("\n", `lsblk -o label -pn $devpath`);
    if(exists $labels[1] && $labels[1] eq $wantedpartitions->[0]->{label}) { return 1; } else { return undef; } #$label[1] because $labels[0] is $devpath itself
}


#Creates a description key for a hash as described in show_info_about_device and returns the description
sub create_device_description {
    my $deviceinfo = shift;
    my $description = $deviceinfo->{removable} ? "Removable " : "Non-removable ";
    $description .= $deviceinfo->{size} . " ";
    if($deviceinfo->{cibu}) {
        $description .= "device with a CIBU installation (that I can reinstall/update) ";
    } else {
        $description .= "device without CIBU ";
    }
    if($deviceinfo->{model} ne "") {
        $description .= "($deviceinfo->{model})";
    }
    return $description;
}

#Returns a hash with as keys the available block devices and as values hashes as described in show_info_about_device
sub find_available_block_devices {
    my @blockdevices = split("\n", `lsblk -pndo NAME,RM,SIZE,MODEL`);
    my $infoallblockdevices = {};
    foreach(@blockdevices) {
        if(/^(\S+)\s+(\d)\s+(\S+)\s+(.*)\s*$/) {
            my $path = $1; my $removable = $2; my $size = $3; my $model = $4;
            next if($path =~ /^\/dev\/sr\d+$/); #Skip CD/DVD drives
            $infoallblockdevices->{$path} = { path => $path, removable => $removable, size => $size, model => $model, cibu => is_cibu_device($path) };
            $infoallblockdevices->{$path}->{description} = create_device_description($infoallblockdevices->{$path});
          }
    }
    return $infoallblockdevices;
}

#Accepts a hash with info about the device and prints the description and the output of 'fdisk -l' for the device.
#The hash has the following keys: 'path', 'removable' (1 if it is), 'size' (human readable), 'model', 'cibu' (1 if it is a CIBU-device) and 'description'
#Returns undef if fdisk fails, otherwise returns 1.
sub show_info_about_device {
    my $devinfo = shift;
    say "";
    say "Device '$devinfo->{path}' is a $devinfo->{description}.";
    say "The partition layout according to fdisk is :";
    my $fdiskoutput = `fdisk -l $devinfo->{path} 2>&1`;
    if($? == 0) {
        say $fdiskoutput;
        return 1;
    } else {
        $fdiskoutput =~ s/^\s*fdisk:\s*(.*)\s*$/$1/;
        say "WARNING: Failed to get a lot of info for $devinfo->{path}. Don't use this blockdevice. This error should tell you why -> $fdiskoutput";
        return undef;
    }
}

#Asks the user to choose a block device from a list of available block devices or to enter a path to a block device. Returns the chosen block device path.
#If the user enters 0 or a path that is not a block device the script will be cancelled with an error message.
#The last number will be used to show detailed info of all block devices and afterwards this function will be called again.
#When we implement the option to create a disk image file in the future, the check for a block device will be removed
sub choose_device {
    if($settings->{devicepath}) {
        unless(-b $settings->{devicepath}) {
            myerror "The device path you specified with the -d option is not a block device. Please specify a valid block device path.";
        }
        return $settings->{devicepath};
    }
    my $devsinfo = find_available_block_devices();
    my @sorteddevpaths = sort keys %$devsinfo;
    my @options = ("Cancel");
    foreach my $devpath (@sorteddevpaths) {
        push @options, "$devpath -> $devsinfo->{$devpath}->{description}";
    }
    mysay << "END";
Choose the number of a blockdevice to install CIBU on. Choose option 0 to cancel.
You can also enter the full path. This will be useful IN THE FUTURE if you want to create a disk image file instead of a physical block device.
(Disk images is a feature that is not yet implemented)
END
    my $i;
    for($i=0; $i<@options; $i++) {
        say "[$i] $options[$i]";
    }
    say "[$i] Show detailed info of all block devices above first";
    print "Choose a optionnumber or enter a path: "; my $answer = <STDIN>; chomp $answer;
    if($answer =~ /^\s*0\s*$/) {  #The first option is not part of @devices
        say "Script cancelled by user."; exit(1);
    } elsif($answer =~ /^\s*$i\s*$/) {  #Neither is the last
        show_info_about_device($devsinfo->{$_}) foreach(@sorteddevpaths);
        return choose_device();
    } elsif($answer =~ /^\s*(\d+)\s*$/ && exists $options[$1]) {
        deviceinfo_and_confirmation($devsinfo->{$sorteddevpaths[$1-1]}); # -1 because the devices start counting at 1 in the options
        return $sorteddevpaths[$1-1];
    } elsif($answer =~ /^\s*(\S.*?)\s*$/ && -b $1) {
        return $1;
    } else {
        myerror "Invalid input. Please enter a valid number or path to a (existing) file or block device.";
    }
}

#Checks if any of the partitions on the given device are mounted. If a mounted partition is found, prints an error message and exits with code 1.
sub check_if_mounted {
    my $devpath = shift;
    mysay "Checking if any partitions on '$devpath' are mounted...";
    my @partitions = `lsblk -o mountpoint -n $devpath`;
    foreach(@partitions) {
        chomp;
        unless(/^\s*$/) {
            print <<END;    #We don't use myerror because no warning about mountpoints is needed.

Sorry, quiting... $devpath has one or more partitions that are still mounted. (I already found a partition mounted at '$_').
Please unmount all partitions on the device before running this script.
(At this point in the script I don't umount things myself for safety reasons.
When the device get's new partitions later, I will do mounting and umounting myself)
END
            exit(1);
        }
    }
    mysay "No partitions on '$devpath' are mounted";
}

#Prints some information about the given device (as hash as described in show_info_about_device) and asks the user to confirm
sub deviceinfo_and_confirmation {
    my $devinfo = shift;
    mysay "You have chosen to install on '$devinfo->{path}', here is some information about it:";
    unless(show_info_about_device($devinfo)) {
        mysay "Please do not continue, See the line above. But...";
    }
    ask_for_confirmation("\nIf you are sure you have chosen the correct device, then please enter 'yes' to confirm and continue, otherwise enter 'no' to cancel: ");
}

#Finds the partitions on the given device and returns them as a list.
sub find_partitions_on_device {
    my $devpath = shift;
    my $fdisk_output = `fdisk -l $devpath`;
    my @partitions;
    foreach(split("\n", $fdisk_output)) {
        if(/^\s*($devpath\d+)\s+/) {
            push @partitions, $1;
        }
    }
    return \@partitions;
}

#Wipes the filesystem signatures of the partitions on the given devices, wipes the partition table and creates a new GPT partition table
sub wipe_and_create_table {
    my ($devpath, $ddlength) = @_;
    my $partitions = find_partitions_on_device($devpath);
    mysay "Wiping '$devpath' and creating a new GPT partition table on it...";
    foreach(@$partitions) {
        mysystem("dd if=/dev/zero of=$_ $ddlength && sync"); #Wipe the beginning of each partition, $ddlength is a combination of the bs and count options of dd
    }
    mysystem("sgdisk --zap-all $devpath"); #Wipe the partition table
    mysystem("sgdisk --mbrtogpt $devpath"); #Create a new GPT partition table
    mysystem("partprobe $devpath && sleep 3"); # Tell the OS about the new partition table
    mysay "$devpath has been wiped and a new GPT partition table has been created on it.";
}

#Creates 3 partitions on the device given
#The 3rd partition will receive the special GUID and typecode needed for GRUB to use it as BIOS Boot partition
sub create_partitions {
    my $devpath = shift;
    my $cibupartsize = $wantedpartitions->[0]->{size};
    my $biospartsize = $wantedpartitions->[2]->{size};
    mysay "Creating the 3 partitions on '$devpath' needed by CIBU.";
    mysay "The 1st partition will be used for CIBU and will have a size of $cibupartsize, the 2nd partition for the iso files and the 3rd partition will be used as the BIOS Boot partition by GRUB.";
    mysystem("sgdisk --new=1:0:+$cibupartsize --typecode 1:ef00 $devpath"); # Create the first partition, starting at the beginning of the device, and using the specified size
    mysystem("sgdisk --new=3:-$biospartsize:0 --typecode=3:ef02 --partition-guid=3:21686148-6449-6E6F-744E-656564454649 $devpath"); # Create the third partition, starting at the end of the device, and using the specified size.
    #The 3rd partition will be used as the BIOS Boot partition by GRUB, so we have to make sure that it is 1MB, uses 21686148-6449-6E6F-744E-656564454649 as special GUID and typecode ef02 to indicate this
    mysystem("sgdisk --new=2:0:0 $devpath"); # Create the second partition, using the remaining space on the device
    mysystem("partprobe $devpath && sleep 3"); #Tell the OS about the new partitions
    mysay "The 3 partitions needed by CIBU have been created on '$devpath'.";
}

#Formats $partition according to $wantpartentry (it's entry in $wantedpartitions)
sub mkfs {
    my ($partition, $wantpartentry) = @_;
    mysay "Formatting $partition as $wantpartentry->{label}";
    my $mkfscmd = $wantpartentry->{mkfs};
    $mkfscmd=~s/WANTEDLABEL/$wantpartentry->{label}/; $mkfscmd=~s/PARTPATH/$partition/;
    mysystem($mkfscmd);
    mysay("Partition $partition has been formatted as $wantpartentry->{label}");
}

#Labels and formats the partitions on the device given as 1st argument. The 2nd argument is the wanted partition layout (see the Settings-section).
#Returns a arrayref with the paths of the first and second partition
sub name_and_format_partitions {
    my ($devpath) = @_;
    my $cibupartname = $wantedpartitions->[0]->{label};
    my $isopartname = $wantedpartitions->[1]->{label};
    my $biospartname = $wantedpartitions->[2]->{label};
    mysay "Naming and formatting the partitions on '$devpath'.";
    mysay "The first partition will be named '$cibupartname' and formatted as FAT32, the second partition will be named '$isopartname' and formatted as ext4, and the third partition will be named 'BIOS Boot' and left unformatted.";
    mysystem("sgdisk --change-name=1:'$cibupartname' $devpath");
    mysystem("sgdisk --change-name=2:'$isopartname' $devpath");
    mysystem("sgdisk --change-name=3:'$biospartname' $devpath");
    mysystem("partprobe $devpath && sleep 3"); #Tell the OS about the new partition names, before we format them
    mysay "Naming the partions on '$devpath' is done. Now formatting the partitions...";
    my ($cibupart, $isopart) = @{find_partitions_on_device($devpath)}[0,1];   #Partitions are not always just the device followed by a number
    mkfs($cibupart, $wantedpartitions->[0]);
    mkfs($isopart, $wantedpartitions->[1]);
    mysystem("partprobe $devpath && sleep 3"); #Tell the OS about the new partition changes
    mysay "The partitions on '$devpath' have been named and formatted.";
    return [$cibupart, $isopart];
}

#Checks if grub2-install or grub-install is available on the system, and returns a hash with a key 'installer' with this command as value.
#This hash also has a key 'configdir' that has the name of the grub config directory of the grub on your system as value (not the full path, only the ending which should be 'grub2' or 'grub').
#If neither grub2-install nor grub-install is found, prints an error message and exits with code 1.
sub grub_grub2_choice {
    mysay "Checking for grub or grub2";
    my $grubversion = {};
    my $path = `which grub2-install 2>/dev/null`;
    if($? == 0 && $path =~ /^\/.*grub2-install$/) {
        mysay "Found grub2-install";
        $grubversion->{installer} = 'grub2-install';
        $grubversion->{configdir} = 'grub2';
    } else {
        $path = `which grub-install 2>/dev/null`;
        if($? == 0 && $path =~ /^\/.*grub-install$/) {
            mysay "Found 'grub-install'";
            $grubversion->{installer} = 'grub-install';
            $grubversion->{configdir} = 'grub';
        } else {
            myerror "'grub2-install' or grub-install commands not found.";
        }
    }
    return $grubversion;
}

#Unmounts the partitions passed as arguments if they are mounted. If a partition is not mounted, it will be skipped. If a partition is mounted multiple times, they will all be unmounted.
sub umount {
    my @partitions = @_;
    mysay "Checking if any of the following partitions are mounted and unmounting them if they are: @partitions";
    my $mountoutput = `mount`;
    if($? != 0) {
        myerror "Failed to get mount output.";
    }
    my $mounts = {};
    foreach(split("\n", $mountoutput)) {
        if(/^\s*(\S+)\s+on\s+(\S+)/) {
            if(exists $mounts->{$1}) {
                push @{$mounts->{$1}}, $2;
            } else {
                $mounts->{$1} = [$2];
            }
        }
    }
    foreach my $part (@partitions) {
        if(exists $mounts->{$part}) {
            foreach my $mnt (@{$mounts->{$part}}) {
                mysay "Unmounting $part from $mnt";
                mysystem("umount $mnt");
            }
        }
    }
    mysay "All specified partitions are now unmounted.";
}

#Mount the partition passed as an argument on a temporary directory and returns the absolute path of the mountpoint.
sub mount {
    my $partition = shift;
    mysay "Mounting $partition...";
    my $dir = `mktemp -d ${tmpmountpointprefix}XXXXXX`; chomp($dir);
    myerror "Failed to create temporary directory for mounting $partition." if($? != 0);
    mysystem("mount $partition $dir");
    mysay "$partition is now mounted on $dir.";
    return $dir;
}

#Checks if the grub on the system has support for BIOS and/or EFI boot mode by checking if the directories /usr/lib/grub/i386-pc and /usr/lib/grub/x86_64-efi exist.
#Returns a hash with keys 'BIOS' and 'EFI' with value 1 if support for that boot mode is found. If no support for either boot mode is found, prints an error message and exits with code 1.
sub check_bios_efi_support {
    my $support = {};
    $support->{BIOS} = 1 if( -d '/usr/lib/grub/i386-pc');
    $support->{EFI} = 1 if( -d '/usr/lib/grub/x86_64-efi');
    if(keys(%$support) == 0) {
        myerror "Neither support for BIOS or EFI was found in your grub";
    }
    if(exists $support->{BIOS}) {
        mysay "Grub BIOS support found.";
    } else {
        mysay "WARNING: no /usr/lib/grub/i386-pc dir. Skipping Grub BIOS support";
    }
    if(exists $support->{EFI}) {
        mysay "Grub EFI support found.";
    } else {
        mysay "WARNING: no /usr/lib/grub/x86_64-efi dir. Skipping Grub EFI support";
    }
    return $support;
}

#Installs GRUB on the given device and partition, for the boot modes supported by the grub on the system.
#1st argument is the grub installer command to use (grub-install or grub2-install),
#2nd argument is the hash with the supported boot modes returned by the check_bios_efi_support function
#3rd argument is the mountpoint of the first partition on which the boot files will be installed
#4th argument is the device on which to install grub
sub install_grub {
    my ($grubinstaller, $support, $part1mountpoint, $devpath) = @_;
    if(exists $support->{BIOS}) {
        mysay "Installing GRUB for BIOS boot mode...";
        mysystem("$grubinstaller --target=i386-pc --boot-directory '$part1mountpoint/boot' $devpath");
        mysay "GRUB installed for BIOS boot mode.";
    }
    if(exists $support->{EFI}) {
        mysay "Installing GRUB for EFI boot mode...";
        mysystem("$grubinstaller --target=x86_64-efi --removable --no-nvram --efi-directory '$part1mountpoint' --boot-directory '$part1mountpoint/boot' $devpath");
        mysay "GRUB installed for EFI boot mode.";
    }
}

#Copies the GRUB configuration files from the directory in the 1st argument to the directory in the 2nd argument. It is expected that:
# - The from-directory should be the absolute path of the grub2 config directory that is located in the same directory as this script
# - The to-directory is 'boot/grub' or 'boot/grub2' on the mounted first partition of the device, depending on the grub version found on the system. Also as absolute path.
sub copy_grub_config {
    my ($fromdir, $todir) = @_;
    mysay "Copying GRUB configuration to the device...";
    mysystem("rsync -rt --delete --exclude=i386-pc --exclude=x86_64-efi --exclude=fonts -- $fromdir/ $todir/");
    mysay "GRUB configuration copied.";
}

#Creates the directory layout for the ISO files. It is expected that:
# - The 1st argument is the partition that will be used for the ISO files. It is expected that this partition already has the correct label and (empty) filesystem.
# - The 2nd argument is the absolute path of the grub config directory on the first partition of the device. It is expected that CIBU is installed and that it's mounted
#   The distro config files in the grub2 config directory there should be named in the format 'inc-<distroname>.cfg'.
# - The 3rd argument is the name of the directory that will be created on the second partition to put the ISO files in.
# - The 4rd argument is a hash with the uid and gid of the user who invoked sudo
# The result will be a directory named $isosdir with for each <distroname> a subdir. And they will all get the UID and GID of the user who invoked sudo.
# Returns the mount point of the partition with the isos
sub create_isos_dirs {
    my ($isospart, $grubconfigdir, $isosdir, $user) = @_;
    mysay "Creating the directory layout for the partition for ISO files...";
    mysay ""; umount($isospart); #Just in case it's automounted
    my $isosmnt = mount($isospart);
    for my $distroconfig (glob("$grubconfigdir/*")) {
        $distroconfig =~ /^.*\/inc-(\S+)\.cfg$/ or next;
        mysystem("mkdir -p '$isosmnt/$isosdir/$1'");
    }
    mysystem("chown -R $user->{uid}:$user->{gid} '$isosmnt/$isosdir'");
    mysay "Directory layout for ISO files created. (A dir name '$isosdir' with subdirs for each distro where you can put the ISO files for that distro)";
    return $isosmnt;
}

#Create a new cibu device but don't install the cibu system on it yet.
#$wantedpartitions is the partition layout (see the Settings-section), $ddlength is the length (as dd options) that will be wiped with dd in the beginning of all old partitions
#Returns a arrayref with the path of the partition with the cibu system and the path of the partition for the ISO files.
sub create_new_device {
    my ($devpath, $ddlength) = @_;
    mysay "Preparing a device for CIBU creation...";
    mysay ""; check_if_mounted($devpath);
    mysay ""; wipe_and_create_table($devpath, $ddlength);
    mysay ""; create_partitions($devpath);
    mysay ""; my ($cibupart, $isopart) = @{name_and_format_partitions($devpath)};
    mysay "Device '$devpath' is now ready for CIBU installation. The partition with the CIBU system is '$cibupart' and the partition for the ISO files is '$isopart'.";
    return [$cibupart, $isopart];
}

#Installs cibu on a device that already has the correct partition table.
#First argument is the device, 2nd argument the cibu partition, 3rd is the dir where the grub config files are located
#It is expected that the cibu partition already has the correct label and (empty) filesystem. Returns the mountpoint of the cibu partition
sub install_cibu {
    my ($devpath, $cibupart, $grubconfigdir) = @_;
    mysay "Installing CIBU on the device...";
    mysay ""; my $grubversion = grub_grub2_choice();
    mysay ""; umount($cibupart); #Just in case it's automounted
    mysay ""; my $cibumnt = mount($cibupart);
    mysay ""; my $support = check_bios_efi_support();
    mysay ""; install_grub($grubversion->{installer}, $support, $cibumnt, $devpath);
    mysay ""; copy_grub_config($grubconfigdir, "$cibumnt/boot/$grubversion->{configdir}");
    return $cibumnt;
}

#If $devpath is not a $cibudevice, prepares it using create_new_device(). (see info there about the arguments)
#If it is, it just formats the CIBUSYS pratition unless it's asked for a full reinstall in which case it also calls create_new_device()
#In both case an arrayref with the paths of the partition of the cibusystem and that of the one with the iso files is returned
sub create_device_if_wanted {
    my ($devpath, $ddlength) = @_;
    my $createdevice = 1;
    if(is_cibu_device($devpath)) {
        mysay "The device you have chosen already has a CIBU installation on it. You can choose to wipe device completely or just do a reinstall/update";
        mysay "If you choose to skip wiping, your partition with the ISO files will be kept intact";
        print "Enter 'yes' to reinstall/update the CIBU system on the first partition so that you keep the partition with the ISO files intact: ";
        if($settings->{force}) {
            mysay "Force option is set, automatically choosing to reinstall/update the CIBU system on the first partition so that you keep the partition with the ISO files intact.";
            $createdevice = undef;
        } else {
            $createdevice = undef if(<STDIN> =~ /^\s*y(es)?\s*$/i);
        }
    }
    if($createdevice) {
        mysay ""; return create_new_device($devpath, $ddlength);
    }
    mysystem("sgdisk -t 1:ef00 $devpath"); #Set type code for EFI because old CIBU versions didn't do this.
    my ($cibupart, $isopart) = @{find_partitions_on_device($devpath)}[0,1];   #Partitions are not always just the device followed by a number
    mkfs($cibupart, $wantedpartitions->[0]); # Format the first partition as FAT32, and set its label
    mysystem("partprobe $devpath && sleep 3"); #Tell the OS about the new partition changes
    return [$cibupart, $isopart];
}

#Create the ramdisk at $initrd_result based on the contents of $initrd_contentdir. Most distro's will not need this
#We can add this ramdisk in the initrd list of grub so that the file "/cibu-init" inside this becomes available
#If you do this (and tell the kernel to run /cibu-init as PID 1) it will then make sure that the the iso you use becomes available as /dev/loop0.
#This way "annoying" iso's (e.g. Alpine) can use this /dev/loop0 as device with the root filesystem
#Afer /cibu-init has done it job it will switch to the real /init and continue booting as normal.
sub create_initrd {
    my ($initrd_contentdir, $initrd_result) = @_;

    my $tempdir = tempdir(CLEANUP => 1) or myerror "Failed to create temporary directory: $!";
    mysystem("rsync -rp $initrd_contentdir/ $tempdir/");
    mysystem("cd $tempdir && find . -print0 | cpio --null -ov --format=newc | gzip -9 > $initrd_result");
}


#Read the commandline options and return a hash with the settings.
sub read_commandline_options {
    my @args = @ARGV;
    my $settings = {};
    while(@args) {
        my $arg = shift @args;
        $settings->{help} = 1 if $arg eq '-h' || $arg eq '--help';
        $settings->{force} = 1 if $arg eq '-f' || $arg eq '--force';
        $settings->{quiet} = 1 if $arg eq '-q' || $arg eq '--quiet';
        if($arg eq '-d' || $arg eq '--device') {
            if(@args > 0) {
                $settings->{devicepath} = shift @args;
            } else {
                myerror "Option '$arg' requires a device path as argument.";
            }
        }
    }
    return $settings;
}

#Show a help for CIBU
sub show_help {
    print << "END";
CIBU - Cross-ISO Boot Utility
Usage: $0 [options]
Options:
  -h, --help          Show this help message and exit
  -f, --force         Force the script to run without asking for confirmation
  -q, --quiet         Run in quiet mode (only absolute necessary output)
  -d, --device <path> Specify the block device to use
END
    exit(0);
}

#Find the dir with the cibu binary (follow all symlinks) and return it (without trailing slash)
sub find_dir_with_cibu_binary {
    my $location = $0;
    $location = readlink($location) while (-l $location);
    $location =~ s/\/[^\/]+$//;
    return $location;
}


$settings = read_commandline_options();
show_help() if $settings->{help};
my $user = run_as_root();
showdisclaimer();
unless($settings->{force} or $settings->{quiet}) {
    ask_for_confirmation("Have you read, understood & fully accepted the disclaimer and the rest of the text above ?\nPlease enter 'yes' to accept and continue, otherwise enter 'no' to cancel: ");
}
mysay ""; check_available_programs(qw(lsblk fdisk sgdisk partprobe mkfs.fat mkfs.ext4 mount mktemp rsync mount umount mkdir chown cpio gzip find));
mysay ""; my $devpath = choose_device();
mysay ""; my ($cibupart, $isopart) = @{create_device_if_wanted($devpath, $ddlength)};
my $cibudir = find_dir_with_cibu_binary(); my $grubconfigdir = "$cibudir/grub2";
mysay ""; my $cibumnt = install_cibu($devpath, $cibupart, $grubconfigdir);
mysay ""; create_initrd("$cibudir/extra_initrds/alpine", "$cibumnt/alpine-initrd");
mysay ""; create_initrd("$cibudir/extra_initrds/nixos", "$cibumnt/nixos-initrd");
mysay ""; my $isosmnt = create_isos_dirs($isopart, $grubconfigdir, $isosdir, $user);
#Finishing up
mysay ""; umount($cibupart, $isopart);
mysay ""; mysystem("rm -rf '$cibumnt' '$isosmnt'"); #Remove the temporary mountpoints
mysay "All done ! You can now copy your ISO files to the '$isosdir' directory on the second partition of the device and boot from it to use CIBU. (The partition is '$isopart and has the label '$wantedpartitions->[1]->{label}')";
